
# cargo-vet audits file

[audits]

[[trusted.forensicnomicon-core]]
criteria = "safe-to-deploy"
user-id = 347968 # Albert Hui (h4x0r)
start = "2026-06-28"
end = "2027-08-04"

[[trusted.peripheral-core]]
criteria = "safe-to-deploy"
user-id = 347968 # Albert Hui (h4x0r)
start = "2026-06-13"
end = "2027-08-04"
